// Generated by scripts/encode-promo-videos.mjs. Do not edit by hand.
// Arts listed here play a silent ping-pong film from public/promo/video; the
// value versions its URLs.
import type { PromoArtKey } from './PromoArt';

export const PROMO_VIDEOS: Partial<Record<PromoArtKey, string>> = {
  automation: '33008cedd8',
  branding: 'a02fba2fa1',
  contact: 'd7c72e2ec6',
  ecommerce: '1b74872839',
  facemapping: 'f75563eef9',
  film: '74e7f14c37',
  genai: '2a8ada076b',
  heritage: '20ef8d3607',
  history: 'f268ab16f7',
  jetson: '9d000a030b',
  live: '89b466dacc',
  paul: '4edf7e8068',
  rag: 'bb182d32af',
  video: '7d4b05feb3',
  voice: 'd095d194fd',
  wojna1939: 'bf55867970',
  xr: '627290505e',
};
