'use client';

import React, { useEffect, useRef, useState } from 'react';
import { useReducedMotion } from '@/lib/hooks';
import { PROMO_VIDEOS } from './promoVideos';

/**
 * Banner artwork for the studio promos, cropped to fill the banner. Arts with
 * a film (components/promoVideos.ts, generated by scripts/encode-promo-videos.mjs)
 * play it silently in a seamless ping-pong loop from /public/promo/video; the
 * rest show a WebP still from /public/promo.
 *
 * Artwork provenance is documented in assets/promo-sources/README.md.
 * AI-assisted artwork is labelled.
 *
 * Decorative only: the promo copy next to it carries the meaning, so the media
 * is aria-hidden and has an empty alt.
 */

export type PromoArtKey =
  | 'automation'
  | 'voice'
  | 'rag'
  | 'jetson'
  | 'wojna1939'
  | 'film'
  | 'video'
  | 'xr'
  | 'facemapping'
  | 'live'
  | 'history'
  | 'ecommerce'
  | 'branding'
  | 'genai'
  | 'heritage'
  | 'paul'
  | 'contact';

interface ArtMeta {
  /** Generated or substantially altered by AI: labelled on screen. */
  ai: boolean;
  /** A real photograph that AI altered, rather than a generated picture. */
  altered?: boolean;
  /** Where the subject sits, for crops that cannot show the whole frame. */
  focus?: string;
  zoom?: number;
}

export const PROMO_ART: Record<PromoArtKey, ArtMeta> = {
  automation: { ai: true },
  voice: { ai: true },
  rag: { ai: true },
  jetson: { ai: true, focus: '64% 50%' },
  wojna1939: { ai: true, focus: '68% 50%' },
  film: { ai: true },
  video: { ai: true },
  xr: { ai: true },
  facemapping: { ai: true },
  live: { ai: true },
  history: { ai: true },
  ecommerce: { ai: true },
  branding: { ai: true },
  genai: { ai: true },
  heritage: { ai: true },
  paul: { ai: true, altered: true, focus: '68% 35%' },
  contact: { ai: true },
};

/** The most specific true disclosure, per the brand's AI labelling rules. */
export function aiLabel(art: PromoArtKey) {
  // Every film is generated from a still, the portrait's included.
  if (PROMO_VIDEOS[art]) return 'Wideo wygenerowane przez AI.';
  return PROMO_ART[art].altered ? 'Obraz zmieniony z pomocą AI.' : 'Obraz wygenerowany przez AI.';
}

/** Rendition per placement: the phone banner and the full-screen desktop stage. */
export type PromoFilmSize = '720' | '1080';

/** The still: a film's first frame as its poster, otherwise the WebP artwork. */
export function promoArtSrc(art: PromoArtKey) {
  const film = PROMO_VIDEOS[art];
  if (film) return `/promo/video/${art}.webp?v=${film}`;
  if (art === 'paul') return '/promo/paul.webp?v=20261001-gold';
  const regenerated: PromoArtKey[] = ['automation', 'voice', 'rag', 'wojna1939', 'video', 'xr', 'facemapping', 'live', 'history', 'ecommerce', 'branding', 'genai', 'contact'];
  return `/promo/${art}.webp${regenerated.includes(art) ? '?v=20261001-fhd' : ''}`;
}

export function hasPromoFilm(art: PromoArtKey) {
  return Boolean(PROMO_VIDEOS[art]);
}

/** Films only when motion is welcome and data is not scarce: never for reduced
    motion, Save-Data or a 2G link. Client only. */
function filmsWelcome() {
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return false;
  const connection = (navigator as Navigator & { connection?: { saveData?: boolean; effectiveType?: string } }).connection;
  return !connection?.saveData && !/2g$/.test(connection?.effectiveType ?? '');
}

const AV1 = 'video/webm; codecs="av01.0.08M.08"';
const formats = new Map<PromoFilmSize, Promise<'webm' | 'mp4'>>();

/**
 * AV1 WebM, about a third lighter, where the browser decodes it: always on the
 * desktop stage, on the phone banner only with hardware decoding, to spare the
 * battery. H.264 MP4 everywhere else, Safari without AV1 hardware included.
 */
function filmFormat(size: PromoFilmSize) {
  let format = formats.get(size);
  if (!format) {
    format = (async () => {
      if (!document.createElement('video').canPlayType(AV1)) return 'mp4';
      if (size === '1080' || !navigator.mediaCapabilities) return 'webm';
      try {
        const info = await navigator.mediaCapabilities.decodingInfo({
          type: 'file',
          video: { contentType: AV1, width: 1280, height: 720, bitrate: 600_000, framerate: 24 },
        });
        return info.supported && info.powerEfficient ? 'webm' : 'mp4';
      } catch {
        return 'webm';
      }
    })();
    formats.set(size, format);
  }
  return format;
}

type Film = { job: Promise<string | null>; users: number; used: number };
const films = new Map<string, Film>();
/** Downloaded films kept in memory when no layer shows them. */
const KEEP_IDLE = 4;

function sweepFilms() {
  const idle = [...films.entries()].filter(([, film]) => film.users === 0).sort((a, b) => b[1].used - a[1].used);
  for (const [key, film] of idle.slice(KEEP_IDLE)) {
    films.delete(key);
    void film.job.then((url) => url && URL.revokeObjectURL(url));
  }
}

/**
 * Downloads a film whole, in the background, and resolves to a blob URL that
 * plays at once and loops without touching the network again. Resolves to
 * null for arts without a film, when films are unwelcome, or on failure; the
 * still shows then.
 */
export function loadPromoFilm(art: PromoArtKey, size: PromoFilmSize): Promise<string | null> {
  const version = PROMO_VIDEOS[art];
  if (!version || !filmsWelcome()) return Promise.resolve(null);
  const key = `${art}-${size}`;
  let film = films.get(key);
  if (!film) {
    const job = filmFormat(size)
      .then((format) => fetch(`/promo/video/${art}-${size}.${format}?v=${version}`, {
        signal: typeof AbortSignal.timeout === 'function' ? AbortSignal.timeout(60_000) : undefined,
      }))
      .then((response) => (response.ok ? response.blob() : Promise.reject(new Error(`HTTP ${response.status}`))))
      .then((blob) => URL.createObjectURL(blob))
      .catch(() => {
        films.delete(key);
        return null;
      });
    film = { job, users: 0, used: 0 };
    films.set(key, film);
  }
  film.used = Date.now();
  sweepFilms();
  return film.job;
}

/**
 * True once the art is ready to show without waiting: its film downloaded and
 * its still decoded. Used to hold the next card back until it can play.
 */
export function usePromoReady(art: PromoArtKey | null, size: PromoFilmSize) {
  const [readyArt, setReadyArt] = useState<PromoArtKey | null>(null);

  useEffect(() => {
    if (!art) return;
    let live = true;
    const still = new window.Image();
    still.src = promoArtSrc(art);
    void Promise.all([loadPromoFilm(art, size), still.decode().catch(() => {})]).then(() => {
      if (live) setReadyArt(art);
    });
    return () => {
      live = false;
    };
  }, [art, size]);

  return art !== null && readyArt === art;
}

/** The art's film as a blob URL once downloaded, kept in memory while shown. */
function useFilmUrl(art: PromoArtKey, size: PromoFilmSize) {
  const reducedMotion = useReducedMotion();
  const [url, setUrl] = useState<string | null>(null);

  useEffect(() => {
    setUrl(null);
    if (!PROMO_VIDEOS[art] || !filmsWelcome()) return;
    let live = true;
    const job = loadPromoFilm(art, size);
    const film = films.get(`${art}-${size}`);
    if (film) film.users += 1;
    void job.then((value) => {
      if (live) setUrl(value);
    });
    return () => {
      live = false;
      if (film) {
        film.users -= 1;
        film.used = Date.now();
      }
      sweepFilms();
    };
  }, [art, size, reducedMotion]);

  return url;
}

/**
 * The promo picture: a muted, inline, looping film where one exists, the still
 * until it has downloaded and otherwise. The film's poster is its first frame,
 * so the change is invisible. If the browser refuses autoplay (iOS Low Power
 * Mode) or cannot decode the film, the still stays.
 */
export function PromoMedia({
  art,
  size,
  focus = '50% 50%',
  className = '',
}: {
  art: PromoArtKey;
  size: PromoFilmSize;
  focus?: string;
  className?: string;
}) {
  const url = useFilmUrl(art, size);
  const [failed, setFailed] = useState(false);
  const videoRef = useRef<HTMLVideoElement>(null);
  const playing = url !== null && !failed;

  useEffect(() => {
    const video = videoRef.current;
    if (!playing || !video) return;
    // Autoplay rules check the property, which React does not always set.
    video.muted = true;
    video.play().catch((error: DOMException) => {
      if (error.name !== 'AbortError') setFailed(true);
    });
  }, [playing, url]);

  const style: React.CSSProperties = {
    objectPosition: PROMO_ART[art].focus ?? focus,
    transform: PROMO_ART[art].zoom ? `scale(${PROMO_ART[art].zoom})` : undefined,
  };
  const classes = `h-full w-full object-cover select-none ${className}`;

  if (playing) {
    return (
      <video
        ref={videoRef}
        src={url}
        poster={promoArtSrc(art)}
        muted
        loop
        autoPlay
        playsInline
        preload="auto"
        disablePictureInPicture
        disableRemotePlayback
        aria-hidden="true"
        tabIndex={-1}
        onError={() => setFailed(true)}
        className={classes}
        style={style}
      />
    );
  }

  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={promoArtSrc(art)}
      alt=""
      aria-hidden="true"
      decoding="async"
      draggable={false}
      className={classes}
      style={style}
    />
  );
}

/**
 * The brand's AI marker (hx-ai, overlay variant): a gold "AI" tab and the
 * exact wording, on a solid dark plate in a corner of the frame.
 */
export function AiBadge({ art, className = '' }: { art: PromoArtKey; className?: string }) {
  return (
    <span
      className={`chamfer chamfer-sm chamfer-line inline-flex items-center gap-2 border border-white/[0.16] bg-[#0a0a0c]/[0.62] py-1 pl-1 pr-3 text-[11px] font-medium leading-tight text-white backdrop-blur-[12px] ${className}`}
    >
      <span className="grid h-[1.6em] min-w-[1.9em] place-content-center bg-accent px-1 font-label font-bold tracking-[0.06em] text-[#0a0a0c]">
        AI
      </span>
      {aiLabel(art)}
    </span>
  );
}

export default function PromoArt({ art }: { art: PromoArtKey }) {
  return <PromoMedia art={art} size="720" />;
}
