import {
  closeSync,
  existsSync,
  mkdirSync,
  openSync,
  statSync,
  writeSync,
} from 'fs';
import { join } from 'path';
import { UPLOADS_DIR } from '../config';

export function ensureUploadsDir(): void {
  if (!existsSync(UPLOADS_DIR)) mkdirSync(UPLOADS_DIR, { recursive: true });
}

export function transferDir(transferId: string): string {
  return join(UPLOADS_DIR, transferId);
}

/**
 * On-disk name for a payload. Generated by us, never derived from user input,
 * which is what makes path traversal structurally impossible.
 */
export function storageNameFor(fileIndex: number): string {
  return `f${String(fileIndex).padStart(5, '0')}.bin`;
}

export function storagePath(transferId: string, storageName: string): string {
  return join(transferDir(transferId), storageName);
}

/** Archive produced by the pre-rework backend; still served for old links. */
export function legacyArchivePath(transferId: string): string {
  return join(UPLOADS_DIR, `${transferId}.zip`);
}

export function legacyChunksDir(transferId: string): string {
  return join(UPLOADS_DIR, `${transferId}_chunks`);
}

/**
 * Writes a chunk at its absolute position in the target file, so parallel and
 * out-of-order chunk uploads need no temporary files and no reassembly pass.
 */
export function writeChunkAt(path: string, offset: number, data: Uint8Array): void {
  let fd: number;
  try {
    fd = openSync(path, 'r+');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
    try {
      fd = openSync(path, 'wx'); // exclusive create, loser of the race retries
    } catch (createError) {
      if ((createError as NodeJS.ErrnoException).code !== 'EEXIST') throw createError;
      fd = openSync(path, 'r+');
    }
  }

  try {
    writeSync(fd, data, 0, data.byteLength, offset);
  } finally {
    closeSync(fd);
  }
}

export function fileSizeOrNull(path: string): number | null {
  try {
    return statSync(path).size;
  } catch {
    return null;
  }
}
